### ISSUE TITLE
Assembling the puzzle

### ISSUE THREAD

**Issue by PaintIt** [smay1613/15-puzzleQt#5]
`isBoardValid` method only works for second and eighth position
you can do this: 

`void GameBoard::shuffle()
{
    auto seed = std::chrono::system_clock::now().time_since_epoch().count();
    static std::mt19937 g(seed);
    do {
        std::shuffle(m_raw_board.begin(), m_raw_board.end(), g);

        if(!(m_raw_board.at(hiddenElementIndex()) == m_raw_board[0])){
            std::swap(m_raw_board.at(7), m_raw_board.at(hiddenElementIndex()));
        }
    }
    while (!isBoardValid());
    emit dataChanged(index(0, 0), index(m_boardsize - 1, 0));
}`

**Comment by smay1613** [comment]
Is it still valid? Please create pull request, thanks!
